language: go

go:
  - 1.2
  - 1.3

env:
  - PGPASSWORD=tokenserver

addons:
  postgresql: "9.3"

before_script:
  - psql -c "create user tokenserver with password 'tokenserver';" -U postgres
  - psql -c 'create database tokenserver owner tokenserver;' -U postgres
  - psql -f setup.sql -U tokenserver -d tokenserver

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -repotoken kMZDPrdqpOKa3CXHCwgCz4pmqqKgzojXv

